DROP TABLE USERS IF EXISTS;

CREATE TABLE USERS (
    USER_ID VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR_IGNORECASE(50) NOT NULL,
    PASSWORD VARCHAR_IGNORECASE(50) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    GENDER VARCHAR_IGNORECASE(50) NOT NULL,
    JOIN_DATE TIMESTAMP NOT NULL
);

DROP TABLE USER_ROLE IF EXISTS;

CREATE TABLE USER_ROLE (
    USER_ID VARCHAR_IGNORECASE(50) NOT NULL,
    USER_ROLE VARCHAR_IGNORECASE(50) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    MODIFY_DATE TIMESTAMP NOT NULL,
);
