INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('jack', 'Jack Bauer', '1234!@#$', true, 'M', NOW());
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('chloe', 'Chloe O Brian', '1234!@#$', true, 'F', NOW());
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('kim', 'Kim Bauer', '1234!@#$', true, 'F', NOW());
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('david', 'David Palmer', '1234!@#$', true, 'M', NOW());
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('michelle', 'Michelle Dessler', '1234!@#$', true, 'M', NOW());

INSERT INTO USER_ROLE (USER_ID, USER_ROLE, CREATE_DATE, MODIFY_DATE) VALUES ('jack', 'ROLE_NORMAL', NOW(), NOW());
INSERT INTO USER_ROLE (USER_ID, USER_ROLE, CREATE_DATE, MODIFY_DATE) VALUES ('jack', 'ROLE_ADMIN', NOW(), NOW());
INSERT INTO USER_ROLE (USER_ID, USER_ROLE, CREATE_DATE, MODIFY_DATE) VALUES ('chloe', 'ROLE_ADMIN', NOW(), NOW());